export const autoCompleteArray = [
    'Avengers',
    'Batman',
    'Superman',
    'Wonder Woman',
    'Guardians of the Galaxy',
    'Prometheus',
    'Split',
    'Sing',
    'Suicide Squad',
    'The Great Wall',
    'La La Land',
    'Mindhorn',
    'The Lost City of Z',
    'Passengers',
    'Fantastic Beasts and Where to Find Them',
    'Hidden Figures',
    'Rogue One',
    'Moana',
    'Colossal',
    'The Secret Life of Pets',
    'Hacksaw Ridge',
    'Jason Bourne',
    'Lion',
    'Arrival'
]